In [1]:
import numpy as np
import pandas as pd

In [2]:
l=[1,2,3,4]

In [3]:
arr=np.array(l)   #list conver to array

In [4]:
arr              #One Dimensional array

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4],[5,6]])             #Two Dimensional array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [8]:
np.asanyarray([1,2,3,4,2,3])

array([1, 2, 3, 4, 2, 3])

In [9]:
mtx=np.matrix([2,3,2,3,4])

In [10]:
np.asanyarray(mtx)    #Matrix is not convert to array because it is already in array

matrix([[2, 3, 2, 3, 4]])

### opration in array

In [11]:
a=np.array([1,2,3,4])

In [12]:
c=a

In [13]:
c

array([1, 2, 3, 4])

In [14]:
a

array([1, 2, 3, 4])

In [15]:
c[0]=100

In [16]:
c

array([100,   2,   3,   4])

In [17]:
a

array([100,   2,   3,   4])

In [18]:
d=np.copy(a)         #Make Anothere array with Address

In [19]:
d

array([100,   2,   3,   4])

In [20]:
a[0]=400

In [21]:
a

array([400,   2,   3,   4])

In [22]:
c

array([400,   2,   3,   4])

In [23]:
d

array([100,   2,   3,   4])

## Some Function in array

In [24]:
np.fromfunction(lambda i,j:i==j,(3,3))  ##--             --
                                        # | 11    12   13  |
                                        # | 21    22   23  |
                                        # | 31    32   33  |
                                        # --             --

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [25]:
np.fromfunction(lambda i,j:i*j,(3,3))    # -- 0     1    2--
                                        # 0| 0     0    0  |
                                        # 1| 0     1    2  |
                                        # 2| 0     2    4  |
                                        #  --             --

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [26]:
iterable=(i*i for i in range(5))
iterable

<generator object <genexpr> at 0x0000026B4EDE76D0>

In [27]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [28]:
np.fromstring('1 3 4 5 5 5 5',sep=' ')

array([1., 3., 4., 5., 5., 5., 5.])

### Numpy data types 

In [29]:
l=[1,2,3,1,4,2,5,3]

In [30]:
ar=np.array(l)
ar

array([1, 2, 3, 1, 4, 2, 5, 3])

In [31]:
np.ndim(ar)      #to find the dimension of array

1

In [32]:
ar.size

8

In [33]:
ar.shape

(8,)

In [34]:
ar.dtype

dtype('int32')

In [35]:
ar2=np.array([[1.0,2,3,4,5],[6,7,8,9,0]])
ar2

array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]])

In [36]:
ar2.dtype

dtype('float64')

In [37]:
ar3=np.arange(2.3,5.6)
ar3

array([2.3, 3.3, 4.3, 5.3])

In [38]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
ar4=np.zeros((2,3))           #2-D Array
ar4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
ar5=np.zeros((3,4,2))       #3-D Array
ar5

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [41]:
ar6=np.zeros((3,4,2,3))
ar6

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [42]:
print(ar3.ndim,"dimension")
print(ar4.ndim,"dimension")
print(ar5.ndim,"dimension")
print(ar6.ndim,"dimension")

1 dimension
2 dimension
3 dimension
4 dimension


In [43]:
np.ones(4)

array([1., 1., 1., 1.])

In [44]:
ar7=np.ones((2,3))

In [45]:
ar7*4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [46]:
np.empty((3,5))       #For empty array 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
np.eye(4)              #Identity matrix in array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.logspace(2,5,10,base=2)      #To find logarithm value

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [49]:
arr=np.random.rand(3,5)       #for Randam Array 

In [50]:
pd.DataFrame(arr)

0         1         2         3         4
0  0.700472  0.112639  0.075398  0.143631  0.388449
1  0.198711  0.074882  0.664915  0.593822  0.774279
2  0.044390  0.519104  0.118514  0.711418  0.099208

In [51]:
np.random.randn(3,5)          #based on standard Normal distribution , Where the mean is 0 and the standard deviation is 1

array([[ 0.02154947, -1.15484607, -0.80816449, -1.31260798,  0.92430162],
       [-0.40547156,  0.60520269,  2.03456547, -0.86042028,  0.12487527],
       [-0.95545046, -0.27667065, -0.39432368, -1.15501541,  0.01358754]])

In [52]:
pd.DataFrame(np.random.randint(1,110,(300,400)))    #to store:- to_csv('Test.csv')

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     30    2   95   19   21   23   68    8   26   68  ...   43   84  109   
1     37   95   97    9   29   79   28    4   37   91  ...  100  109   14   
2    109   49  103  103   93   68   52   35   53   49  ...   85   30   40   
3     59   65   21   38   50    9    5   69    6  101  ...   94   23   55   
4     15  101   88   45   81   31   13   59  103   41  ...   20    1   88   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   96  104   13   12    6   29  101  105   66   34  ...   12   84   58   
296   29    8   56   25   21   23   91   26  108   58  ...   81   15   61   
297   47   30   69    8   81   30   49   89   83   30  ...   61   39   62   
298   16   62    1   49   16   48   46  102   96   66  ...  102  104  107   
299   92   83   37   57   48  101   92   82   51   76  ...   42    2   92   

     393  394  395  396  397  398  399  
0     29   34   85   73   52   44   56  
1     32   48   87   48  103   19    8  
2     49   26  102   78   45   36   76  
3     47   58   72    4   42   52   25  
4      3   96   57   61   98   49    8  
..   ...  ...  ...  ...  ...  ...  ...  
295    2   19   16   17   35   79  109  
296   37   95    8    4   89   20   76  
297    9   28   68   33   60   76   85  
298  107   48   50   45   13   87   93  
299   65   39  105   92    5   14   98  

[300 rows x 400 columns]

In [53]:
ay=np.random.rand(3,4)   # Array have 12 element

In [54]:
aee=ay.reshape(6,2)         #this reshape array also have 12 element

In [55]:
aee

array([[0.11672453, 0.94580614],
       [0.05623624, 0.30037966],
       [0.45322201, 0.23972897],
       [0.38564644, 0.94386481],
       [0.77512713, 0.80238901],
       [0.91203595, 0.9865411 ]])

In [56]:
aee[1][0]                #to get data from array

0.056236235297485226

In [57]:
aee[2:5,0]              #toget data [row,Column]

array([0.45322201, 0.38564644, 0.77512713])

In [58]:
ay1=np.random.randint(1,100,(5,6))

In [59]:
ay1

array([[29, 42, 46, 90,  8, 31],
       [27, 76, 70, 50, 18, 65],
       [62, 48, 14, 65, 36, 38],
       [40, 82, 45, 29, 12, 91],
       [32, 71, 63,  1, 36, 14]])

In [60]:
ay1[ay1>50]            #to find grater then less then element in array

array([90, 76, 70, 65, 62, 65, 82, 91, 71, 63])

In [61]:
ay1[2:4,(1,2)]    #Get sub array from array [row{:},(column{,})]

array([[48, 14],
       [82, 45]])

##  maths Opration in array

In [62]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [63]:
arr1

array([[2, 1, 2],
       [1, 1, 2],
       [1, 2, 1]])

In [64]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 2]])

In [65]:
arr1+arr2

array([[3, 2, 3],
       [3, 3, 4],
       [2, 4, 3]])

In [66]:
arr1-arr2

array([[ 1,  0,  1],
       [-1, -1,  0],
       [ 0,  0, -1]])

In [67]:
arr1*arr2       # Simpal multiplication (Not matrix)

array([[2, 1, 2],
       [2, 2, 4],
       [1, 4, 2]])

In [68]:
arr1@arr2      #Matrix Multiplication

array([[6, 8, 8],
       [5, 7, 7],
       [6, 7, 7]])

In [69]:
arr1/arr2

array([[2. , 1. , 2. ],
       [0.5, 0.5, 1. ],
       [1. , 1. , 0.5]])

In [70]:
arr1/0

C:\Users\admin\AppData\Local\Temp\ipykernel_11220\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [71]:
arr1+100

array([[102, 101, 102],
       [101, 101, 102],
       [101, 102, 101]])

In [72]:
arr1**2        #2 in power

array([[4, 1, 4],
       [1, 1, 4],
       [1, 4, 1]])

## Numpy - Broadcasting

In [73]:
arr=np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
row=np.array([1,2,3,4])

In [75]:
arr+row         #row wise Broadcasting

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [76]:
col=np.array([[1,2,3,4]])

In [77]:
col.T+arr                #column wise broadcasting

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [78]:
arr1=np.random.randint(1,4,(3,4))
arr1

array([[3, 3, 3, 2],
       [3, 1, 3, 1],
       [2, 1, 1, 1]])

In [79]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.41421356],
       [1.73205081, 1.        , 1.73205081, 1.        ],
       [1.41421356, 1.        , 1.        , 1.        ]])

In [80]:
np.exp(arr1)

array([[20.08553692, 20.08553692, 20.08553692,  7.3890561 ],
       [20.08553692,  2.71828183, 20.08553692,  2.71828183],
       [ 7.3890561 ,  2.71828183,  2.71828183,  2.71828183]])

In [96]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.30103   ],
       [0.47712125, 0.        , 0.47712125, 0.        ],
       [0.30103   , 0.        , 0.        , 0.        ]])

In [97]:
arr1.flatten()         #flat the array

array([3, 3, 3, 2, 3, 1, 3, 1, 2, 1, 1, 1])

In [99]:
arr1.ndim

2

In [100]:
arr2=np.array([1,2,3,4])

In [101]:
arr2

array([1, 2, 3, 4])

In [107]:
np.expand_dims(arr2,axis=1).ndim          #Expand dimension

2

In [108]:
np.expand_dims(arr2,axis=0)

array([[1, 2, 3, 4]])

In [111]:
np.squeeze(arr1).ndim   #Every row contect one to more element .so not work 

2

In [112]:
data=np.array([[1],[2],[3]])

In [113]:
data

array([[1],
       [2],
       [3]])

In [115]:
np.squeeze(data).ndim    #In this array element is minmam so we easyly 

1

In [116]:
np.repeat(data,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [121]:
np.roll(arr2,2)

array([3, 4, 1, 2])

In [126]:
np.diag(arr2)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### mathematical/Binarey operations 

In [127]:
arr1

array([[3, 3, 3, 2],
       [3, 1, 3, 1],
       [2, 1, 1, 1]])

In [128]:
arr2

array([1, 2, 3, 4])

In [131]:
arr2=np.random.randint(1,5,(3,4))

In [132]:
arr2

array([[2, 2, 2, 4],
       [4, 4, 1, 3],
       [1, 4, 3, 4]])

In [133]:
arr1+arr2

array([[5, 5, 5, 6],
       [7, 5, 4, 4],
       [3, 5, 4, 5]])

In [135]:
arr1-arr2

array([[ 1,  1,  1, -2],
       [-1, -3,  2, -2],
       [ 1, -3, -2, -3]])

In [136]:
arr1%arr2

array([[1, 1, 1, 2],
       [3, 1, 0, 1],
       [0, 1, 1, 1]])

In [138]:
arr1/arr2

array([[1.5       , 1.5       , 1.5       , 0.5       ],
       [0.75      , 0.25      , 3.        , 0.33333333],
       [2.        , 0.25      , 0.33333333, 0.25      ]])

In [139]:
arr1**arr2

array([[ 9,  9,  9, 16],
       [81,  1,  3,  1],
       [ 2,  1,  1,  1]])

In [140]:
arr1&arr2

array([[2, 2, 2, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 0]])

In [141]:
arr1|arr2

array([[3, 3, 3, 6],
       [7, 5, 3, 3],
       [3, 5, 3, 5]])

In [142]:
~arr1

array([[-4, -4, -4, -3],
       [-4, -2, -4, -2],
       [-3, -2, -2, -2]])

In [143]:
arr1<arr2

array([[False, False, False,  True],
       [ True,  True, False,  True],
       [False,  True,  True,  True]])

In [144]:
## mathematical function

In [145]:
np.sin(arr1)

array([[0.14112001, 0.14112001, 0.14112001, 0.90929743],
       [0.14112001, 0.84147098, 0.14112001, 0.84147098],
       [0.90929743, 0.84147098, 0.84147098, 0.84147098]])

In [146]:
np.cos(arr1)

array([[-0.9899925 , -0.9899925 , -0.9899925 , -0.41614684],
       [-0.9899925 ,  0.54030231, -0.9899925 ,  0.54030231],
       [-0.41614684,  0.54030231,  0.54030231,  0.54030231]])

In [147]:
np.tan(arr1)

array([[-0.14254654, -0.14254654, -0.14254654, -2.18503986],
       [-0.14254654,  1.55740772, -0.14254654,  1.55740772],
       [-2.18503986,  1.55740772,  1.55740772,  1.55740772]])

In [148]:
np.tanh(arr1)

array([[0.99505475, 0.99505475, 0.99505475, 0.96402758],
       [0.99505475, 0.76159416, 0.99505475, 0.76159416],
       [0.96402758, 0.76159416, 0.76159416, 0.76159416]])

In [149]:
np.min(arr1)

1

In [150]:
np.max(arr1)

3

In [151]:
np.mean(arr1)

2.0

In [152]:
np.median(arr1)

2.0

In [153]:
np.power(arr1,2)

array([[9, 9, 9, 4],
       [9, 1, 9, 1],
       [4, 1, 1, 1]], dtype=int32)

In [154]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.30103   ],
       [0.47712125, 0.        , 0.47712125, 0.        ],
       [0.30103   , 0.        , 0.        , 0.        ]])

In [155]:
np.exp(arr1)

array([[20.08553692, 20.08553692, 20.08553692,  7.3890561 ],
       [20.08553692,  2.71828183, 20.08553692,  2.71828183],
       [ 7.3890561 ,  2.71828183,  2.71828183,  2.71828183]])

In [156]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.41421356],
       [1.73205081, 1.        , 1.73205081, 1.        ],
       [1.41421356, 1.        , 1.        , 1.        ]])

### Numpy- String Functions

In [160]:
new=np.array(['rohit','aman'])          #dtype='<U5= u5 means eqvalent to the string

In [161]:
np.char.capitalize(new)

array(['Rohit', 'Aman'], dtype='<U5')

In [162]:
np.char.upper(new)

array(['ROHIT', 'AMAN'], dtype='<U5')

In [163]:
np.char.title(new)

array(['Rohit', 'Aman'], dtype='<U5')

### short,Search & Counting Function

In [165]:
arr=np.array([1,2,34,10,5,6,789,32,98,76,54,2,7])

In [166]:
arr

array([  1,   2,  34,  10,   5,   6, 789,  32,  98,  76,  54,   2,   7])

In [168]:
np.sort(arr)

array([  1,   2,   2,   5,   6,   7,  10,  32,  34,  54,  76,  98, 789])

In [170]:
np.searchsorted(arr,43)

6

In [171]:
len(arr)

13

In [173]:
arr1=([0,0,0,0,234,0,0,0,3,0,0,0,765,0,0,0])

In [175]:
np.count_nonzero(arr1)

3

In [176]:
arr

array([  1,   2,  34,  10,   5,   6, 789,  32,  98,  76,  54,   2,   7])

In [177]:
np.where(arr>10)

(array([ 2,  6,  7,  8,  9, 10], dtype=int64),)

In [179]:
np.extract(arr>10,arr)

array([ 34, 789,  32,  98,  76,  54])

### Numpy - Byte Swapping

In [181]:
arr.byteswap()

array([  16777216,   33554432,  570425344,  167772160,   83886080,
        100663296,  352518144,  536870912, 1644167168, 1275068416,
        905969664,   33554432,  117440512])

### Numpy - Copies & Views

In [183]:
arr

array([  1,   2,  34,  10,   5,   6, 789,  32,  98,  76,  54,   2,   7])

In [184]:
a=np.copy(arr)    # deep copy

In [185]:
b=arr.view()      # solo copy{b=arr}

In [186]:
b

array([  1,   2,  34,  10,   5,   6, 789,  32,  98,  76,  54,   2,   7])

In [187]:
arr

array([  1,   2,  34,  10,   5,   6, 789,  32,  98,  76,  54,   2,   7])

In [188]:
arr[1]=21

In [189]:
b

array([  1,  21,  34,  10,   5,   6, 789,  32,  98,  76,  54,   2,   7])

### Numpy- Matrix Library

In [190]:
import numpy.matlib as nm

In [191]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [192]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [193]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Numpy- Linear Algebra

In [194]:
arr1=np.random.randint([[2,3],[4,5]])

In [195]:
arr2=np.random.randint([[5,3],[3,5]])